version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: circleci/node@5.0.2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker file
          command: |
            docker build . -t app
  my-job-name:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          sudo apt install curl
          node bin/www
          sleep 5
          curl localhost:8080/users
workflows:
  my-custom-workflow:
    jobs:
      - build
      - my-job-name :
          requires:
           - build